<?php
return [
  "Afghanistan",
  "South Africa",
  "Albania",
  "Algeria",
  "Germany",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Saudi Arabia",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Belarus",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Chile",
  "China",
  "Cyprus",
  "Colombia",
  "Comoros",
  "Congo (Brazzaville)",
  "Congo (Kinshasa)",
  "North Korea",
  "South Korea",
  "Costa Rica",
  "Ivory Coast",
  "Croatia",
  "Cuba",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Egypt",
  "El Salvador",
  "United Arab Emirates",
  "Ecuador",
  "Eritrea",
  "Spain",
  "Estonia",
  "United States",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Ghana",
  "Greece",
  "Grenada",
  "Greenland",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guinea",
  "Equatorial Guinea",
  "Guinea-Bissau",
  "Guyana",
  "French Guiana",
  "Haiti",
  "Honduras",
  "Hungary",
  "India",
  "Indonesia",
  "Iraq",
  "Iran",
  "Ireland",
  "Iceland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kyrgyzstan",
  "Kiribati",
  "Kuwait",
  "Laos",
  "Lesotho",
  "Latvia",
  "Lebanon",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malaysia",
  "Malawi",
  "Maldives",
  "Mali",
  "Malta",
  "Morocco",
  "Martinique",
  "Mauritius",
  "Mauritania",
  "Mayotte",
  "Mexico",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Mozambique",
  "Namibia",
  "Nauru",
  "Nepal",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norway",
  "New Caledonia",
  "New Zealand",
  "Oman",
  "Uganda",
  "Uzbekistan",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Netherlands",
  "Peru",
  "Philippines",
  "Poland",
  "French Polynesia",
  "Portugal",
  "Qatar",
  "Hong Kong SAR",
  "Macau SAR",
  "Central African Republic",
  "Czech Republic",
  "Dominican Republic",
  "Réunion",
  "Romania",
  "United Kingdom",
  "Russia",
  "Rwanda",
  "Western Sahara",
  "Saint Barthélemy",
  "Saint Kitts and Nevis",
  "San Marino",
  "Saint Martin (French part)",
  "Saint Martin (Dutch part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Saint Helena",
  "Saint Lucia",
  "Samoa",
  "American Samoa",
  "Sao Tome and Principe",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Somalia",
  "Sudan",
  "South Sudan",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Suriname",
  "Syria",
  "Tajikistan",
  "Tanzania",
  "Taiwan",
  "Chad",
  "Thailand",
  "East Timor",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkmenistan",
  "Turkey",
  "Tuvalu",
  "Ukraine",
  "Uruguay",
  "Vanuatu",
  "Vatican",
  "Venezuela",
  "Vietnam",
  "Wallis and Futuna",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];
